name: Build

on: push

jobs:

  x86:
    name: x86
    runs-on: ubuntu-20.04
    steps:
      - name: Set env
        run: echo "RELEASE_TAG=$(date +%Y%m%d)" >> $GITHUB_ENV
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install packages
        run: |
          sudo dpkg --add-architecture i386
          sudo apt update
          sudo apt install -y -o Acquire::Retries=50 \
                           mtools syslinux isolinux \
                           libc6-dev-i386 libc6-dbg:i386 valgrind
      - name: Build (BIOS)
        run: |
          make -j 4 -C src bin-i386-pcbios/undionly.kpxe
      - name: Build (UEFI)
        run: |
          make -j 4 -C src bin-x86_64-efi/ipxe.efi
      - name: Build (LKRN)
        run: |
          make -j 4 -C src bin-i386-pcbios/ipxe.lkrn
      - name: Test
        run: |
          make -j 4 -C src 		bin-i386-linux/tests.linux
          make -j 4 -C src bin-x86_64-linux/tests.linux
          valgrind ./src/bin-i386-linux/tests.linux
          valgrind ./src/bin-x86_64-linux/tests.linux
      - name: Release
        uses: softprops/action-gh-release@v1
        if: github.ref == 'refs/heads/master'
        with:
          name: $RELEASE_TAG
          tag_name: $RELEASE_TAG
          files: |
            ./src/bin-i386-pcbios/undionly.kpxe
            ./src/bin-x86_64-efi/ipxe.efi
            ./src/bin-i386-pcbios/ipxe.lkrn
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
